version: '3'

services:
  app:
    build: 
      context: ./client
      dockerfile : Dockerfile
    ports:
      - "3000:3000"
    volumes:
    - ./client:/usr/src/app/client
    - /usr/src/app/client/node_modules

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-nextcom}
    ports:
      - "5432:5432"